### ISSUE TITLE
Things to fix in the UI

### ISSUE THREAD

**Issue by MoKazino** [MoKazino/MoKazino#3]
Special thanks for sending them to me :heart: 

General 
=======

- [ ] highlighted navigation buttons should reflect the page that is selected. Currently, when any of the navigation buttons are selected, only the "Play" button is highlighted (in orange).
- [ ] h1 and h2 (headers/titles) should be consistent. Currently, "Deposit your XMR" and "Withdraw your XMR" both appear larger than, for example, "Mokazino Bet" (you have "Mokazino Bet" as a h2 class rather than h1 which can create inconsistency).
- [ ] in a windowed browser, the currency switcher button is slightly overlapped by the theme switcher button. These buttons should not overlap.

Play
====

 - [ ] Play (*Change `#1` --> change header title from "Mokazino Bet" to "Play")
 - [ ] (*Change `#2` --> remove MoKazino logo from body of page. *Change `#3` --> change "MIN" button to "Min." button and "MAX" button to "Max." button. *Change `#4` --> change "Bet High" to "Bet high". Change "Bet Low" to "Bet low")

Invest
======

Fees

 - [ ] (*Change `#10` --> change dollar icon next to "XMR Amount" to XMR icon. *Change `#11` --> change "XMR Amount" to "XMR amount". *Change `#12` --> change "MIN" button to "Min." button and "MAX" button to "Max." button)

Invite friends
==============

 - [ ] (*Change `#1` --> remove MoKazino logo from body of page. *Change `#2` --> add orange underline beneath "Invite friends")
